services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dex_sniper-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dex_sniper_db_network

  db:
    image: postgres:15-alpine
    container_name: dex_sniper-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dex_sniper_pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - dex_sniper_db_network

networks:
  dex_sniper_db_network:
    driver: bridge

volumes:
  dex_sniper_pg_data:
