services:
  test-db:
    image: postgres:15-alpine
    container_name: dex_sniper-test-db
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_TEST_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5431
    networks:
      - TEST_db_network

  test-redis:
    image: redis:7.4.2-alpine
    container_name: dex_sniper-test-redis
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${REDIS_PORT}:6378'
    networks:
      - TEST_db_network
    volumes:
      - redis_TEST_data:/data

volumes:
  pg_TEST_data:
  redis_TEST_data:
networks:
  TEST_db_network:
    driver: bridge
