services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: dex_sniper-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dex_network

  db:
    image: postgres:15-alpine
    container_name: dex_sniper-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - dex_network

  pgadmin:
    image: dpage/pgadmin4:9.1
    container_name: dex_sniper-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dex_network

  redis:
    image: redis:7.4.2-alpine
    container_name: dex_sniper-redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - dex_network
    volumes:
      - redis_data:/data

networks:
  dex_network:
    driver: bridge

volumes:
  pg_data:
  redis_data:
